const mongoose = require('mongoose')


const postSchema = new mongoose.Schema({
    caption:{
        type: String,
        maxlength: [2200, "Caption Should be less than 2200 characters"],
        trim: true,
    },
    image:{
        url:{type:String, required: true},
        publicId:{
            type:  String,
            required: true,
        }   //generated by the cloudinary 
    },

    user:{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: [true, "User ID is required"],
    },
    likes:[
        {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',

        }
    ],
    comments: [
        {
          type: mongoose.Schema.Types.ObjectId,
          ref: 'Comment',
        }
      ]
    // createdAt:{
    //     type: Date,
    //     default: Date.now()
    // },
    // due to this our default behaviour is getting overridden so to avoid it comment this out , timestamp also gives us createdAt
}, 
{timestamps: true}

);


postSchema.index({user: 1, createdAt: -1})


const Post = mongoose.model("Post",postSchema);

module.exports = Post;